import SwiftUI
import Observation
import UIKit
import UniformTypeIdentifiers

/// Runs an AI text callable (`summarizeChannel`, `generateHandoff`) for a look-back window.
/// Results are never stored; they live only in this model.
@MainActor
@Observable
final class AiTextRequestModel {
    static let hourOptions = [4, 8, 12, 24, 48]

    var sinceHours: Int
    private(set) var result: AiTextResult?
    private(set) var isWorking = false
    var errorMessage: String?

    private let request: (Int) async throws -> AiTextResult

    init(sinceHours: Int = 12, request: @escaping (Int) async throws -> AiTextResult) {
        self.sinceHours = sinceHours
        self.request = request
    }

    func generate() async {
        guard !isWorking else { return }
        isWorking = true
        errorMessage = nil
        defer { isWorking = false }
        do {
            result = try await request(sinceHours)
        } catch {
            errorMessage = error.userMessage
        }
    }
}

/// Hours picker, Generate button, the AI text with its disclaimer, and a copy action.
/// Meant to sit inside a `List`/`Form`.
///
/// AI text summarizes PHI, so it stays in the app: there is no share sheet, text selection is
/// off, and Copy puts it on the pasteboard as local-only (no Universal Clipboard) for 5 minutes.
struct AiTextSections: View {
    @Bindable var model: AiTextRequestModel
    let generateTitle: String
    /// Kept for source compatibility with callers; sharing is intentionally not offered.
    let shareSubject: String
    @State private var didCopy = false

    var body: some View {
        Section {
            Picker("Look back", selection: $model.sinceHours) {
                ForEach(AiTextRequestModel.hourOptions, id: \.self) { hours in
                    Text("\(hours) hours").tag(hours)
                }
            }
            Button {
                Task { await model.generate() }
            } label: {
                HStack {
                    Label(model.result == nil ? generateTitle : "Regenerate", systemImage: "sparkles")
                    Spacer()
                    if model.isWorking { ProgressView() }
                }
            }
            .disabled(model.isWorking)
        }

        if let error = model.errorMessage {
            Section { ErrorBanner(message: error) }
        }

        if let result = model.result {
            Section {
                Label(result.disclaimer, systemImage: "exclamationmark.shield")
                    .font(.footnote)
                    .foregroundStyle(.orange)
                Text(result.text.nilIfBlank ?? "Nothing to report for this period.")
                    .font(.body)
                    .padding(.vertical, 4)
            } header: {
                Text("Result")
            } footer: {
                if !result.model.isEmpty {
                    Text("Generated by \(result.model). Not saved.")
                }
            }

            Section {
                Button {
                    Self.copyLocally(result.text)
                    didCopy = true
                } label: {
                    Label(didCopy ? "Copied" : "Copy", systemImage: didCopy ? "checkmark" : "doc.on.doc")
                }
            } footer: {
                Text("Copied text stays on this device and is cleared from the clipboard after 5 minutes.")
            }
            .onChange(of: result.text) { _, _ in
                didCopy = false
            }
        }
    }

    /// Local-only (no Handoff / Universal Clipboard), expiring pasteboard copy.
    static func copyLocally(_ text: String) {
        UIPasteboard.general.setItems(
            [[UTType.plainText.identifier: text]],
            options: [.localOnly: true, .expirationDate: Date().addingTimeInterval(300)]
        )
    }
}
