import SwiftUI
import Observation

/// Runs an AI text callable (`summarizeChannel`, `generateHandoff`) for a look-back window.
/// Results are never stored; they live only in this model.
@MainActor
@Observable
final class AiTextRequestModel {
    static let hourOptions = [4, 8, 12, 24, 48]

    var sinceHours: Int
    private(set) var result: AiTextResult?
    private(set) var isWorking = false
    var errorMessage: String?

    private let request: (Int) async throws -> AiTextResult

    init(sinceHours: Int = 12, request: @escaping (Int) async throws -> AiTextResult) {
        self.sinceHours = sinceHours
        self.request = request
    }

    func generate() async {
        guard !isWorking else { return }
        isWorking = true
        errorMessage = nil
        defer { isWorking = false }
        do {
            result = try await request(sinceHours)
        } catch {
            errorMessage = error.userMessage
        }
    }
}

/// Hours picker, Generate button, the AI text with its disclaimer, and copy / share actions.
/// Meant to sit inside a `List`/`Form`.
struct AiTextSections: View {
    @Bindable var model: AiTextRequestModel
    let generateTitle: String
    let shareSubject: String
    @State private var didCopy = false

    var body: some View {
        Section {
            Picker("Look back", selection: $model.sinceHours) {
                ForEach(AiTextRequestModel.hourOptions, id: \.self) { hours in
                    Text("\(hours) hours").tag(hours)
                }
            }
            Button {
                Task { await model.generate() }
            } label: {
                HStack {
                    Label(model.result == nil ? generateTitle : "Regenerate", systemImage: "sparkles")
                    Spacer()
                    if model.isWorking { ProgressView() }
                }
            }
            .disabled(model.isWorking)
        }

        if let error = model.errorMessage {
            Section { ErrorBanner(message: error) }
        }

        if let result = model.result {
            Section {
                Label(result.disclaimer, systemImage: "exclamationmark.shield")
                    .font(.footnote)
                    .foregroundStyle(.orange)
                Text(result.text.nilIfBlank ?? "Nothing to report for this period.")
                    .font(.body)
                    .textSelection(.enabled)
                    .padding(.vertical, 4)
            } header: {
                Text("Result")
            } footer: {
                if !result.model.isEmpty {
                    Text("Generated by \(result.model). Not saved.")
                }
            }

            Section {
                Button {
                    UIPasteboard.general.string = result.text
                    didCopy = true
                } label: {
                    Label(didCopy ? "Copied" : "Copy", systemImage: didCopy ? "checkmark" : "doc.on.doc")
                }
                ShareLink(item: result.text, subject: Text(shareSubject)) {
                    Label("Share", systemImage: "square.and.arrow.up")
                }
            }
            .onChange(of: result.text) { _, _ in
                didCopy = false
            }
        }
    }
}
