import { useMemo, useState } from 'react';
import { query, where } from 'firebase/firestore';
import type { AiTextResult, GenerateHandoffRequest, HandoffScope, Patient } from '@shared/types';
import { useOrgSession } from '../lib/session';
import { orgCol } from '../lib/firestore';
import { useAction, useLiveQuery } from '../lib/hooks';
import { call } from '../lib/firebase';
import { patientName } from '../lib/patient';
import { AiResultView, Button, Card, ErrorBanner, Field, Page } from '../components/ui';

export default function HandoffPage() {
  const s = useOrgSession();
  const act = useAction();
  const [scope, setScope] = useState<HandoffScope>('care_team');
  // Bounded picker: admitted patients only (single-field equality query).
  const patients = useLiveQuery<Patient>(query(orgCol(s.orgId, 'patients'), where('status', '==', 'admitted')), [s.orgId]);
  const mine = useMemo(
    () => patients.data.filter((p) => p.careTeamUids.includes(s.user.uid)).sort((a, b) => patientName(a).localeCompare(patientName(b))),
    [patients.data, s.user.uid],
  );
  const [sinceHours, setSinceHours] = useState(12);
  const [pickMode, setPickMode] = useState<'all' | 'pick'>('all');
  const [selected, setSelected] = useState<string[]>([]);
  const [result, setResult] = useState<AiTextResult | null>(null);

  async function generate() {
    const req: GenerateHandoffRequest = { orgId: s.orgId, sinceHours, scope };
    if (scope === 'care_team' && pickMode === 'pick') {
      if (selected.length === 0) return act.setError('Choose at least one patient.');
      req.patientIds = selected;
    }
    setResult(null);
    let res: AiTextResult | null = null;
    const ok = await act.run(async () => {
      res = await call<GenerateHandoffRequest, AiTextResult>('generateHandoff', req);
    });
    if (ok) setResult(res);
  }

  return (
    <Page title="Shift handoff">
      <Card title="Generate handoff summary">
        <p className="muted">
          {scope === 'care_team'
            ? 'Summarizes your care-team patients (including any who died or were discharged in the window): recent messages, triage calls, visits, timeline events, open tasks and due deadlines.'
            : 'Summarizes your own overnight activity: patients from triage calls you took or were assigned, visits you completed, and calls not linked to a patient.'}{' '}
          The summary is generated by AI, is not stored, and must be verified before use.
        </p>
        <ErrorBanner error={act.error ?? patients.error} />
        <div className="form">
          <div className="form-grid">
            <Field label="Cover">
              <div className="segmented">
                <button type="button" className={scope === 'care_team' ? 'active' : ''} onClick={() => setScope('care_team')}>
                  My care team
                </button>
                <button type="button" className={scope === 'my_activity' ? 'active' : ''} onClick={() => setScope('my_activity')}>
                  My overnight activity
                </button>
              </div>
            </Field>
            <Field label="Look back">
              <select value={sinceHours} onChange={(e) => setSinceHours(Number(e.target.value))}>
                {[8, 12, 24, 48, 72].map((h) => <option key={h} value={h}>Last {h} hours</option>)}
              </select>
            </Field>
            {scope === 'care_team' && (
              <Field label="Patients">
                <div className="segmented">
                  <button type="button" className={pickMode === 'all' ? 'active' : ''} onClick={() => setPickMode('all')}>
                    All my patients ({mine.length})
                  </button>
                  <button type="button" className={pickMode === 'pick' ? 'active' : ''} onClick={() => setPickMode('pick')}>Choose</button>
                </div>
              </Field>
            )}
          </div>
          {scope === 'care_team' && pickMode === 'pick' && (
            <div className="picker">
              {mine.length === 0 && <span className="muted">You are not on any admitted patient's care team.</span>}
              {mine.map((p) => (
                <label key={p.id} className="picker-item">
                  <input
                    type="checkbox"
                    checked={selected.includes(p.id)}
                    onChange={() => setSelected(selected.includes(p.id) ? selected.filter((x) => x !== p.id) : [...selected, p.id])}
                  />
                  {patientName(p)}
                </label>
              ))}
            </div>
          )}
          <div>
            <Button variant="primary" busy={act.busy} onClick={() => void generate()}>Generate handoff</Button>
          </div>
        </div>
      </Card>
      {act.busy && <div className="banner banner-info">Generating… this can take up to a minute.</div>}
      {result && (
        <Card title="Handoff">
          <AiResultView result={result} />
        </Card>
      )}
    </Page>
  );
}
